<!--Statistics-->
		<section class="sptb bg-white">
			<div class="container">
				<div class="section-title center-block text-center">
					<h1>Terms And Conditions For Empanelment Of Hospitals/diagnostic</h1>
				</div>
				<div class="support">
					<div class="row">
					    <P>This agreement sets forth the terms and conditions that apply to the
empanelment of Hospitals/Diagnostic centers/Clinics/Doctors (“Health
Service provider/HSB”) to provide access to health care services by
disseminating healthcare information and data in an unbiased manner
under its scope of licensure or accreditation (Services) to the
users/customers of this Website and its Mobile Application
(collectively be referred to as “Website”), which is managed and
operated by Panacea Techno Services Private Limited (“Company”).
You understand and agree that Company reserves the right to enroll/
appoint other health service providers for similar services as
envisaged herein and you shall have no objection for the same and
vice-versa.</P>
<P>This
document/agreement is an electronic record in terms of Information
Technology Act, 2000 and generated by a computer system and does not
require any physical or digital signatures. This document is
published in accordance with the provisions of Rule 3 of the
Information Technology (Intermediaries guidelines) 2011, that
provides for the due diligence to be exercised for the access or
usage of this Website.</P>
<P>PLEASE
READ THESE TERMS AND CONDITIONS CAREFULLY. YOUR ACCEPTANCE OF TERMS
CONTAINED HEREIN CONSTITUTES THE AGREEMENT BETWEEN YOU AND COMPANY
FOR THE PURPOSE AS DEFINDED HEREUNDER.</P>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%">
1.&nbsp;&nbsp;&nbsp;&nbsp; SCOPE AND PURPOSE</P>
<OL>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Health
	Service Provider is desirous and had approached the Company to
	display/list the information pertaining to the Health Service
	Provider on the Website to disseminate information regarding the
	availability of medical/health facilities with the Health Service
	Provider to the prospective users/customers of the Website and to
	render medical/health care services to the customers of the Company
	who are desirous of availing such medical benefits through the
	Website.</FONT></FONT></P>
	<LI>Parties
	agree that Company shall provide the customer details of such
	customers who have expressed to avail the services of the Health
	Service Provider such as by booking an online consultation, through
	the designated website of the Company.</P>
	<LI>For
	all customers referred by the Company, Company shall be entitled to
	send information through SMS or E-Mail to the SPOC of Service
	Provider.</P>
	<LI>If
	any services, functions or responsibilities not specifically
	described herein or in any related documents but are inherent,
	necessary or customary part of the services or are reasonably
	required for proper performance of the Services in accordance with
	the Agreement, they shall be deemed to be included within the Scope
	of Services as if such services, functions or responsibilities were
	specifically described in this Agreement.</P>
</OL>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%">2. &nbsp;&nbsp;&nbsp;&nbsp; OBLIGATIONS
OF THE SERVICE PROVIDER</P>
<OL>
	<LI>This
	Agreement is between the Health Service Provider and the Company.
	However, it would be applicable to all specialties offered
	by&nbsp;</li><li>Service
	Provider Group of Hospitals/ diagnostic centers/Clinics, as
	may be applicable, and as provided by the Health Service Provider
	from time to time.</li>
	<LI>The empanelled Health Service Provider is expected to provide its
	Services as per the industry standards and in a professional &amp;
	ethical manner.</li>
	<LI>Health Service Provider may set-up a separate Company’s “Co-ordination
	Desk” round the clock in the Health Service Provider Premises, as
	may be mutually agreed with the Company.</li>
	<LI>Health Service Provider shall notify and share with the Company the
	cost/rate list detailing the costs of each medical treatment and
	procedures, which can be suitably displayed on the website of the
	Company. In case of any changes/modification to such costs/rates the
	Service Provider shall notify the same within 2(two) days prior to
	such changes are to be made effective.</li>
	<LI>Health
	Service Provider agrees to provide the Services to the customers of
	the Company with the same degree of care and skill as customarily
	provided to its own patients who are not customers of the Company,
	i.e. according to generally accepted standards of practice including
	medical profession in India.</li>
	<LI>Health
	Service Provider agrees not to discriminate against customers of the
	Company on the basis of race, ethnicity, gender, creed, ancestry,
	lawful occupation, age, religion, marital status, sexual
	orientation, mental or physical disability, medical history, color,
	national origin, place of residence, health status, or any other
	grounds prohibited by law.</li>
	<LI>Health
	Service Provider also agrees to allow Company to audit the relevant
	bills/ documents pertaining to this Agreement; as and when requested
	by the Company. Such auditing shall be scheduled mutually between
	the parties.</LI>
	<LI>Health
	Service Provider shall ensure that the information provided to the
	Company for display on its Website shall be up to dated, true and
	correct. In this context, health Service Provider will not hold the
	Company (including its affiliated companies/group companies and
	related websites) liable for any information relied upon by Company
	as provided by the Health Service Provider.</LI>
	<LI>Health
	Service Provider authorizes Company to collect and receive monies
	towards the amounts payable by the customer for the services
	availed, on behalf of the Service Provider. Further, settlement of
	monies to the Service Provider shall be in accordance with the terms
	as mutually agreed between the parties. All settlements for the
	preceding month shall be made within 60(sixty) days from the
	succeeding month during which the invoice is raised by the Service
	Provider. In this regard, the Service Provider shall raise the
	invoice on or before the 7th day of the successive month for the
	settlement of preceding month.</LI>
	<LI>The
	Health Service Provider shall be solely responsible for any
	misconduct, damage, willfull commission or omission of any services
	which are not listed under these Terms &amp; Conditions or anything
	which goes against the spirit of free, fair and ethical practice of
	patient care.</li>
	<LI><B>Confidentiality :</B>The
	Health Service Provider undertakes to maintain in absolute
	confidence and not to reveal to any person or body, any information
	or data which it receives through and subsequent for providing the
	Services pursuant to this agreement and which pertains; directly or
	indirectly; to the Company or its customers, including the and
	without derogating from the generality of the aforesaid names,
	addresses, details and medical background of the Company’s
	customers, information which pertains to the Company’s business or
	any other data which is proprietary to the Company and its
	customers. It is further agreed that the contents of this
	sub-section cannot derogate from the duty of the Health Service
	Provider in reporting the Company of any data, information or
	medical background which may be relevant to the Company in
	determination of its scope of work. The transfer of information
	shall be in accordance to the procedures established by the Company.
	The Health Service Provider acknowledges that its undertakings given
	in this Agreement with regard to the confidentiality shall be valid
	throughout the Term of this Agreement and it shall abide by the same
	even after the expiry of this Agreement.</li>
</OL>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%">
<B>3.&nbsp;&nbsp;&nbsp;&nbsp;REPRESENTATIONS
AND DECLARATIONS BY THE SERVICE PROVIDER</B></P>
<OL>
	<LI>The
	Health Service Provider declares and undertakes that it has all the
	necessary registrations/ licenses/ approvals/ authorizations
	required by the law in order to provide the medical services
	pursuant to this agreement and that it has adequate ability,
	knowledge, experience and equipment’s required in order to provide
	the said service as required in this agreement.</li>
	<LI>The
	Health Service Provider undertakes to uphold all of the requirements
	of the law as applicable to it from time to time and shall keep
	updated the Company, in case of any significant change in the
	present status of the Provider. The Service Provider also undertakes
	that it shall provide the said services in accordance with the
	provisions of the law and the regulations, which are enacted, from
	time to time, by the central or the state government or the local
	administration/ bodies.</li>
	<LI>The
	Health Service Provider has and will continue to have its facilities
	covered by proper indemnity policy, including error, omission and
	professional indemnity and agrees to keep such policies in force
	during the currency of this Agreement.</li>
	<LI>The
	Health Service Provider declares that it has not been prevented from
	practicing medicines and that no criminal charge of any kind has
	ever been filed against it due to medical malpractice, medical
	negligence and/ or no civil claim has ever been filed against it due
	to damage inflicted during a medical treatment.</li>
	<LI>The
	Health Service Provider also undertakes to inform the Company in the
	event of any complaint of medical malpractice is filed against it
	during the currency of this Agreement.</li>
	<LI>It
	has been duly constituted under the applicable laws and has complied
	with and shall continue to comply with the applicable laws.</li>
	<LI>It
	has the requisite licenses, permissions, authorizations, consents,
	approvals and registrations under the applicable laws and the
	authority to execute this Agreement avail the required Services and
	perform its obligations hereunder.</li>
	<LI>Neither
	the execution and delivery of this Agreement, the consummation of
	the transactions contemplated hereby, or the fulfillment of or
	compliance with the terms and conditions of this Agreement, conflict
	with or result in a breach of or a default under any of the terms,
	conditions or provisions of any legal restriction (including,
	without limitation, any judgment, order, injunction, decree or
	ruling of any court or governmental authority, or any central,
	state, local or other law, statute, rule or regulation) or any
	covenant or agreement or instrument to which it is a Party, or by
	which it is bound, nor does such execution, delivery, consummation
	or compliance violate or result in the violation of its
	constitutional documents.</li>
</OL>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%"><B>4.&nbsp;&nbsp;&nbsp;&nbsp;INTELLECTUAL
PROPERTY RIGHTS</B></FONT></FONT></FONT></P>
<OL>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">The
	Parties hereby acknowledge that each Party is the legal and
	beneficial owner of and has exclusive right, title and interest over
	its own Intellectual Property and all other proprietary information
	in relation to its business. Nothing in this Agreement shall be
	deemed in any way to constitute a transfer or assignment of any
	Intellectual Property by either Party. It is further agreed and
	understood between the Parties that the data and information of
	users/customers produced through this agreement shall jointly owned
	by the Health Service Provider and the Company.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">The
	Health Service Provider hereby grants to the Company a limited,
	non-exclusive, non-transferable right, only for the Term of this
	Agreement, to use the Service Provider’s Intellectual Property,
	including its marks, logos and brand/trade names, solely for in
	relation to the Services to be rendered by the Service Provider in
	accordance with the terms of this Agreement. Subject to the
	confidentiality clause herein, the Company may display on its web
	portals, at all times during the Term of this Agreement, the Health
	Service Provider’s marks, logo and brand/trade names, as mutually
	determined in writing by the Parties solely for purposes specified
	in this Agreement.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Information
	and data of the Health Service Provider shall be published by the
	Company either by relying on the information provided by the Service
	Provider’s or if taken from Health Service Provider’s website
	then by seeking prior written approval from the Health Service
	Provider.</FONT></FONT></FONT></P>
</OL>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%">
<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=4 STYLE="font-size: 13pt"><B>5.&nbsp;&nbsp;&nbsp;&nbsp;INDEMNITY</B></FONT></FONT></FONT></P>
<P>The
Service Provider hereby covenants to indemnify and hold harmless
Company, its employees, servants and agents from and against all
actions, claims, demands, losses, damages, costs and expenses for
which Company shall or may be or become liable in respect of and to
the extent that they arise from:</P>
<OL>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">The
	Health Service Provider committing any breach or contravention of
	the terms and conditions of this Agreement, its obligations under
	this Agreement, applicable Laws, applicable permits, codes,
	ordinances or regulations, bye laws;</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">any
	act of commission or omission, or default on the part of the Service
	Provider and/or its personnel, representatives, officers, agents,
	affiliates;</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">the
	negligent use, misuse, by the health Service Provider or any of its
	employee, servant, agent, with respect to the medical services
	provided to the Customer(s) of the Company;</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="background: #ffffff; line-height: 100%"><FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt">The
	Health Service Provider also agrees to indemnify and hold harmless
	Company from time to time and at all times hereafter, from and
	against, all notices, claims, demands, action, suits or proceedings
	given, made or initiated against Company on account of the Service
	Provider, as also against all costs, charges and expenses suffered
	or incurred by Company as a result of any proceeding or legal action
	filed by the customer or any third party.</FONT></FONT></FONT></P>
</OL>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%">
<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=4 STYLE="font-size: 13pt"><B>6.&nbsp;&nbsp;&nbsp;&nbsp;GENERAL
PROVISIONS</B></FONT></FONT></FONT></P>
<OL TYPE=a>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt"><U><B>Governing
	Law; Dispute Resolution:</B></U></FONT></FONT></FONT><FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">&nbsp;This
	Agreement shall be governed by, and construed in accordance with,
	the laws of India, without regard to the principles of conflict of
	laws of any other jurisdiction. The courts of Gurugram, India which
	shall have exclusive jurisdiction, for remedies available at law to
	such Party.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt"><U><B>Relationship
	of Parties:</B></U></FONT></FONT></FONT><FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">&nbsp;The
	Parties are independent contracting parties and will have no power
	or authority to assume or create any obligation or responsibility on
	behalf of each other. This Agreement will not be construed to create
	or imply any partnership, agency, or joint venture, or
	employer-employee relationship.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt"><U><B>Binding
	Effect; Severability</B></U></FONT></FONT></FONT></P>
	<OL TYPE=i>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">All
		terms and conditions of this Agreement shall be binding upon, inure
		to the benefit of, and be enforceable by the legal representatives,
		successors and assigns of the Parties.</FONT></FONT></FONT></P>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Any
		term or provision of this Agreement that is invalid or
		unenforceable in any jurisdiction will, as to that jurisdiction, be
		ineffective to the extent of such invalidity or unenforceability
		without rendering invalid or unenforceable the remaining terms and
		provisions of this Agreement or affecting the validity or
		enforceability of any of the terms or provisions of this Agreement
		in any other jurisdiction. If any provision of this Agreement is so
		broad as to be unenforceable, the provision will be interpreted to
		be only so broad as is enforceable.</FONT></FONT></FONT></P>
	</OL>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=2 STYLE="font-size: 10pt"><U><B>Entire
	Agreement:</B></U></FONT></FONT></FONT></P>
</OL>
<P ALIGN=JUSTIFY STYLE="margin-bottom: 0.16in; background: #ffffff; line-height: 100%">
<FONT COLOR="#222222"><FONT FACE="inherit, serif"><FONT SIZE=3>This
Agreement constitutes the entire agreement between the Parties
relating to the subject matter of this Agreement and supersedes any
previous written or oral understanding, negotiations, communications
and agreement between the Parties in relation to the matters dealt
with in this Agreement.</FONT></FONT></FONT></P>
<P STYLE="margin-top: 0.21in; margin-bottom: 0in; background: #ffffff; line-height: 100%">
<FONT COLOR="#000000"><FONT FACE="Arial, serif"><FONT SIZE=4 STYLE="font-size: 15pt">CODE
OF CONDUCT</FONT></FONT></FONT></P>
<P STYLE="margin-bottom: 0.16in; background: #ffffff; line-height: 100%">
<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=3>Health
Service Provider:</FONT></FONT></FONT></P>
<OL TYPE=i>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	abide by the Indian Medical Council (Professional conduct, Etiquette
	and Ethics) Regulations, 2002 and other applicable laws to medical
	profession I India</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	ensure that it has the requisite ​qualification recognized by
	Medical Council of India and registered with Medical Council of
	India/State Medical Council (s) is allowed to practice as per the
	applicable laws in India</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	be liable to protect patient/customers privacy and confidentiality
	including any medical information or data provided by the Company’s
	customers.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">who
	participate in telemedicine/online consultation shall ensure and
	maintain an ethical responsibility to uphold fundamental fiduciary
	obligations by disclosing any financial or other interests it has in
	the telemedicine/online consultation application or service and
	shall immediately disclose it to the Company so that Company can
	appropriate steps to manage or eliminate conflicts of interests</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">who
	provide clinical services and/or underwriting decision for health
	and other insurances, through telemedicine must uphold the standards
	of professionalism as are applicable in in-person interactions and
	follow appropriate ethical guidelines and practices as per medical
	laws applicable in India</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">should
	be responsible in understanding the ​current medical condition,
	the past-history, the social history, severity of existing diseases,
	complications and current management line of prospective and current
	customers for health and other insurances.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	be prudent in carrying out a diagnostic evaluation or prescribing
	medication by:</FONT></FONT></FONT></P>
	<UL>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Establishing
		the patient’s identity</FONT></FONT></FONT></P>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Confirming
		that telemedicine services are appropriate for that patient’s
		individual situation and medical needs</FONT></FONT></FONT></P>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Evaluating
		the indication, appropriateness and safety of any prescription in
		keeping with best</FONT></FONT></FONT></P>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">practice
		guidelines and any formulary limitations that apply to the
		electronic interaction</FONT></FONT></FONT></P>
		<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0in; background: #ffffff; line-height: 100%">
		<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">Documenting
		the clinical evaluation and prescription</FONT></FONT></FONT></P>
	</UL>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	attend mandatory in-house training programs that may be conducted by
	the Company from time to time. This may require the Health Service
	Provider to undergo web-based and other training programs. Company
	shall have the right to regularly and monitor and the quality of
	work/service performed by the Health Service Provide.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	maintain all patient related records in an electronic manner in
	accordance with provisions laid down by the Medical Council of India
	and in addition, in the form and manner as instructed by the
	Company.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	keep itself up to date with the developments in medical profession
	and studies,new drugs, treatments and medications, including
	complementary medicine etc.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	at all times maintain a professional appearance and attitude while
	rendeing medical and health care services.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	ensure clear and prompt communication in its dealing with Company’s
	customers.</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	act in utmost good faith and exercise due care, diligence and
	personal and professional integrity in the performance of their
	duties and responsibilities as medical practitioner and shall in no
	event compromise with their independence of judgment</FONT></FONT></FONT></P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-bottom: 0.06in; background: #ffffff; line-height: 100%">
	<FONT COLOR="#222222"><FONT FACE="Arial, serif"><FONT SIZE=2 STYLE="font-size: 10pt">shall
	not exploit for their own personal gain, opportunities that are
	discovered through use of corporate property information</FONT></FONT></FONT></P>
</OL>
<P STYLE="margin-top: 0.21in; margin-bottom: 0.1in; background: #ffffff; line-height: 100%">
<B>Declaration:</B></P>
<P> This is to confirm that we have understood the contents of Company’s Code
of Conduct for Health Service Provider and the same has been
explained and understood by us. We agree and undertake that in
performance of our obligations under this agreement with Company we
shall including but not limited to our officers, directors,
employees, agents, consultants or representatives, etc., shall be
required to adhere to the requirements of this acknowledgement.</P>
					</div>
				</div>
			</div>
		</section>
		<!--/Statistics-->